### ISSUE TITLE
Wallpaper settings resetting

### ISSUE THREAD

**Issue by 4nk1r** [wireless-r/Light-Switch#5] opened 2021-04-04 19:59 UTC
If I set wallpaper settings to custom (**images**) and change system theme using your app, all ringht. But if restart my laptop, wallpaper settings reset!  Then if I change system theme, wallpapers become default **colors** in your app.

Sorry for my English, guess it's bad :|

**Comment by joakimmag** [comment] 2021-04-16 09:16
Thank you for submitting this issue, I'll look into it.

**Comment by joakimmag** [comment] 2021-04-16 18:59
Can you kindly check the version number of your installation and write it here?

**Comment by 4nk1r** [comment] 2021-04-17 02:36
2.1, kinda the last

**Comment by joakimmag** [comment] 2021-04-19 16:10
I've been looking into this and I have not been able to reproduce the issue. Hence I believe the issue is caused by something outside of this program. I'll close this issue, but I can help with troubleshooting in the comments of this thread.

I suspect that Light Switch can't find the wallpaper files after restart. Can you please try the following:

1. Go to `%TMP%\LightSwitch\Wallpapers\` in Explorer.
2. Check for the presence of wallpaper image files: (1) after you set Preferences, and (2) after restart. Are the wallpaper files there before and after restart?

**Closed as completed by joakimmag** 2021-04-19 16:10 UTC
